### ISSUE TITLE
StandardError: switchToWindow failed.

### ISSUE THREAD

**Issue by mockdeep** [dequelabs/axe-core-gems#233]
We see occasional errors in our builds when running `axe-core`:

<details>
  <summary>Stack trace</summary>

```
     Failure/Error: expect(page).to be_axe_clean.skipping(*a11y_skip) if accessible
     
     Minitest::UnexpectedError:
       StandardError: switchToWindow failed. Are you using updated browser drivers? Please check out https://github.com/dequelabs/axe-core-gems/blob/develop/error-handling.md
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/api/run.rb:82:in `rescue in within_about_blank_context'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/api/run.rb:75:in `within_about_blank_context'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/api/run.rb:38:in `analyze_post_43x'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/core.rb:18:in `call'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/matchers/be_axe_clean.rb:22:in `audit'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/axe-core-api-4.4.0/lib/axe/matchers/be_axe_clean.rb:26:in `matches?'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
           /home/circleci/app/spec/support/accessibility_overrides.rb:25:in `click_on'
           /home/circleci/app/spec/features/_flows/recipient_flow.rb:27:in `recipient_submits_form'
           /home/circleci/app/spec/features/form_filler/attachments_spec.rb:68:in `block (3 levels) in <top (required)>'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.5/lib/active_support/testing/assertions.rb:34:in `assert_nothing_raised'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.5/lib/active_job/test_helper.rb:594:in `perform_enqueued_jobs'
           /home/circleci/app/spec/features/form_filler/attachments_spec.rb:60:in `block (2 levels) in <top (required)>'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `instance_exec'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `block in run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-rails-5.1.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/bin/rspec:25:in `load'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/bin/rspec:25:in `<top (required)>'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
           /home/circleci/.rubygems/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
           /home/circleci/.rubygems/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
           /home/circleci/.rubygems/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
           /home/circleci/.rubygems/bin/bundle:25:in `load'
           /home/circleci/.rubygems/bin/bundle:25:in `<main>'
```
</details>

<pre>
<code>
- `axe-core-rspec` version: 4.4.0
- Firefox 97.0.2
- Capybara w/ RSpec
</code>
</pre>

FYI, we've overridden the default Capybara click helpers to run a11y checks by default:

```rb
module AccessibilityOverrides

  def visit(*args, accessible: true, a11y_skip: [])
    page.visit(*args)
    expect(page).to be_axe_clean.skipping(*a11y_skip) if accessible
  end

  def click_link(*args, accessible: true, a11y_skip: [])
    page.click_link(*args)
    yield if block_given?
    expect(page).to be_axe_clean.skipping(*a11y_skip) if accessible
  end

  def click_button(*args, accessible: true, a11y_skip: [])
    page.click_button(*args)
    yield if block_given?
    expect(page).to be_axe_clean.skipping(*a11y_skip) if accessible
  end

  def click_on(*args, accessible: true, a11y_skip: [])
    page.click_on(*args)
    yield if block_given?
    expect(page).to be_axe_clean.skipping(*a11y_skip) if accessible
  end

end
```

**Comment by michael-siek** [comment]
Hey @mockdeep just following up to see if this is still an issue.

**Comment by mockdeep** [comment]
No, this is in the same class of errors where if we make sure the page is fully loaded we don't see these sorts of errors.

**Comment by padmavemulapati** [comment]
As ` gems` being able to scan the page successfully and nothing is reproducing .


https://github.com/dequelabs/axe-core-gems/assets/47409579/37aac8d8-8556-408a-bc6b-03183b65b881

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems/rspec-cucumber_ |
|**Version** | _4.8.2_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 && Windows 11 _ |
|**BrowserDetails**|_Chrome Version 121.0.6167.139 && Firefox 122.0.1_|
